IVTARGET = IvEngineOGL
IVINCLUDEDIRS = -I../../IvGraphics -I../../IvUtility -I../../IvMath -I../ -I../../.. -I../../../glew-1.12.0/include -I../../../glfw-3.1.1/include
COPYHEADERS = False
COMMONDIR = ../..
TARGETSUFFIX = /OGL
include ../../MakefileCommon
